# The URL the site will be built for
base_url = "https://m-rutter.com"
title = "Some Michael Rutter"
author = "Michael Rutter"
description = "Michael Rutter's personal website - programming, philosophy, and games."
default_language = "en"
output_dir = "public"
compile_sass = true
generate_sitemap = true
generate_robots_txt = true
feed_limit = 20

taxonomies = [
    { name = "tags", paginate_by = 20 }, # 5 items per page for a term
]

[extra]

[markdown.highlighting]
theme = "ayu-dark"
